language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
before_script:
  - git clone https://github.com/php-geospatial/geospatial.git
  - cd geospatial
  - phpize
  - ./configure --enable-geospatial
  - make
  - sudo make install
  - echo "extension=geospatial.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cd ..
install:
  - composer install
script: phpunit --coverage-text